# Require all of the generic RGSSx data structures.
require 'eidolon/rgssx/rpg'

# Require the Ace-specific RGSS3 data structures.
require 'eidolon/rgss3/rpg/bgm'
require 'eidolon/rgss3/rpg/bgs'
require 'eidolon/rgss3/rpg/me'
require 'eidolon/rgss3/rpg/se'
require 'eidolon/rgss3/rpg/base_item'
require 'eidolon/rgss3/rpg/base_item/feature'
require 'eidolon/rgss3/rpg/equip_item'
require 'eidolon/rgss3/rpg/usable_item'
require 'eidolon/rgss3/rpg/actor'
require 'eidolon/rgss3/rpg/class'
require 'eidolon/rgss3/rpg/class/learning'
require 'eidolon/rgss3/rpg/state'
require 'eidolon/rgss3/rpg/enemy'
require 'eidolon/rgss3/rpg/enemy/action'
require 'eidolon/rgss3/rpg/enemy/drop_item'
require 'eidolon/rgss3/rpg/armor'
require 'eidolon/rgss3/rpg/weapon'
require 'eidolon/rgss3/rpg/usable_item/damage'
require 'eidolon/rgss3/rpg/usable_item/effect'
require 'eidolon/rgss3/rpg/item'
require 'eidolon/rgss3/rpg/skill'
require 'eidolon/rgss3/rpg/map/encounter'
require 'eidolon/rgss3/rpg/tileset'
require 'eidolon/rgss3/rpg/system'
require 'eidolon/rgss3/rpg/system/terms'
require 'eidolon/rgss3/rpg/system/test_battler'
require 'eidolon/rgss3/rpg/system/vehicle'