# This file requires all of the internal data structures used by RPG Maker VX.
# Essentially, requiring this file will build a generic copy of the VX data
# structures for use in a Ruby installation outside of VX itself.

require 'eidolon/rgss2/rpg/actor'
require 'eidolon/rgss2/rpg/animation'
require 'eidolon/rgss2/rpg/animation/frame'
require 'eidolon/rgss2/rpg/animation/timing'
require 'eidolon/rgss2/rpg/area'
require 'eidolon/rgss2/rpg/armor'
require 'eidolon/rgss2/rpg/audio_file'
require 'eidolon/rgss2/rpg/base_item'
require 'eidolon/rgss2/rpg/bgm'
require 'eidolon/rgss2/rpg/bgs'
require 'eidolon/rgss2/rpg/class'
require 'eidolon/rgss2/rpg/class/learning'
require 'eidolon/rgss2/rpg/common_event'
require 'eidolon/rgss2/rpg/enemy'
require 'eidolon/rgss2/rpg/enemy/action'
require 'eidolon/rgss2/rpg/enemy/drop_item'
require 'eidolon/rgss2/rpg/event'
require 'eidolon/rgss2/rpg/event/page'
require 'eidolon/rgss2/rpg/event/page/condition'
require 'eidolon/rgss2/rpg/event/page/graphic'
require 'eidolon/rgss2/rpg/event_command'
require 'eidolon/rgss2/rpg/item'
require 'eidolon/rgss2/rpg/map'
require 'eidolon/rgss2/rpg/map_info'
require 'eidolon/rgss2/rpg/me'
require 'eidolon/rgss2/rpg/move_command'
require 'eidolon/rgss2/rpg/move_route'
require 'eidolon/rgss2/rpg/se'
require 'eidolon/rgss2/rpg/skill'
require 'eidolon/rgss2/rpg/state'
require 'eidolon/rgss2/rpg/system'
require 'eidolon/rgss2/rpg/system/terms'
require 'eidolon/rgss2/rpg/system/test_battler'
require 'eidolon/rgss2/rpg/system/vehicle'
require 'eidolon/rgss2/rpg/troop'
require 'eidolon/rgss2/rpg/troop/member'
require 'eidolon/rgss2/rpg/troop/page'
require 'eidolon/rgss2/rpg/troop/page/condition'
require 'eidolon/rgss2/rpg/usable_item'
require 'eidolon/rgss2/rpg/weapon'