# Require all of the generic RGSSx data structures.
require 'eidolon/rgssx/rpg'

# Require the VX-specific RGSS2 data structures.
require 'eidolon/rgss2/rpg/bgm'
require 'eidolon/rgss2/rpg/bgs'
require 'eidolon/rgss2/rpg/me'
require 'eidolon/rgss2/rpg/se'
require 'eidolon/rgss2/rpg/base_item'
require 'eidolon/rgss2/rpg/usable_item'
require 'eidolon/rgss2/rpg/armor'
require 'eidolon/rgss2/rpg/weapon'
require 'eidolon/rgss2/rpg/item'
require 'eidolon/rgss2/rpg/skill'
require 'eidolon/rgss2/rpg/actor'
require 'eidolon/rgss2/rpg/class'
require 'eidolon/rgss2/rpg/class/learning'
require 'eidolon/rgss2/rpg/enemy'
require 'eidolon/rgss2/rpg/enemy/action'
require 'eidolon/rgss2/rpg/enemy/drop_item'
require 'eidolon/rgss2/rpg/state'
require 'eidolon/rgss2/rpg/area'
require 'eidolon/rgss2/rpg/system'
require 'eidolon/rgss2/rpg/system/terms'
require 'eidolon/rgss2/rpg/system/test_battler'
require 'eidolon/rgss2/rpg/system/vehicle'