# This file requires all of the internal data structures used by RPG Maker XP.
# Essentially, requiring this file will build a generic copy of the XP data
# structures for use in a Ruby installation outside of XP itself.

require 'eidolon/rgss/rpg/actor'
require 'eidolon/rgss/rpg/animation'
require 'eidolon/rgss/rpg/animation/frame'
require 'eidolon/rgss/rpg/animation/timing'
require 'eidolon/rgss/rpg/armor'
require 'eidolon/rgss/rpg/audio_file'
require 'eidolon/rgss/rpg/class'
require 'eidolon/rgss/rpg/class/learning'
require 'eidolon/rgss/rpg/common_event'
require 'eidolon/rgss/rpg/enemy'
require 'eidolon/rgss/rpg/enemy/action'
require 'eidolon/rgss/rpg/event'
require 'eidolon/rgss/rpg/event/page'
require 'eidolon/rgss/rpg/event/page/condition'
require 'eidolon/rgss/rpg/event/page/graphic'
require 'eidolon/rgss/rpg/event_command'
require 'eidolon/rgss/rpg/item'
require 'eidolon/rgss/rpg/map'
require 'eidolon/rgss/rpg/map_info'
require 'eidolon/rgss/rpg/move_command'
require 'eidolon/rgss/rpg/move_route'
require 'eidolon/rgss/rpg/skill'
require 'eidolon/rgss/rpg/state'
require 'eidolon/rgss/rpg/system'
require 'eidolon/rgss/rpg/system/test_battler'
require 'eidolon/rgss/rpg/system/words'
require 'eidolon/rgss/rpg/tileset'
require 'eidolon/rgss/rpg/troop'
require 'eidolon/rgss/rpg/troop/member'
require 'eidolon/rgss/rpg/troop/page'
require 'eidolon/rgss/rpg/troop/page/condition'
require 'eidolon/rgss/rpg/weapon'